-- Table: idees_dates
-- Objectif: stocker des idées de dates (CRUD depuis /page5).

create table if not exists public.idees_dates (
  id bigint generated by default as identity primary key,
  title text not null,
  mood text not null default 'romantique',
  place text,
  notes text,
  created_at timestamptz not null default now()
);

-- RLS (recommandé)
alter table public.idees_dates enable row level security;

-- Politiques simples: visibles/modifiables par les utilisateurs authentifiés.
-- (Si vous voulez une app "couple" partagée, c'est souvent suffisant.)
drop policy if exists "idees_dates_select_authenticated" on public.idees_dates;
create policy "idees_dates_select_authenticated"
on public.idees_dates for select
to authenticated
using (true);

drop policy if exists "idees_dates_insert_authenticated" on public.idees_dates;
create policy "idees_dates_insert_authenticated"
on public.idees_dates for insert
to authenticated
with check (true);

drop policy if exists "idees_dates_update_authenticated" on public.idees_dates;
create policy "idees_dates_update_authenticated"
on public.idees_dates for update
to authenticated
using (true)
with check (true);

drop policy if exists "idees_dates_delete_authenticated" on public.idees_dates;
create policy "idees_dates_delete_authenticated"
on public.idees_dates for delete
to authenticated
using (true);

