-- =====================================================================
-- MIGRATION Nanamoureux v2 — alignement avec le nouveau design "Cahier"
-- =====================================================================
-- A exécuter dans l'éditeur SQL de Supabase (Project > SQL Editor).
-- Le script est idempotent (peut être relancé sans casser).
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1) SUPPRESSION DES TABLES INUTILISÉES
--    (repas / corvées ne font pas partie du nouveau design)
-- ---------------------------------------------------------------------
drop table if exists public.corvees_logs;
drop table if exists public.corvees;
drop table if exists public.repas;


-- ---------------------------------------------------------------------
-- 2) COURSES — ajoute "qui a ajouté l'article" (p1/p2)
-- ---------------------------------------------------------------------
alter table public.courses
  add column if not exists by text not null default 'p1' check (by in ('p1', 'p2'));


-- ---------------------------------------------------------------------
-- 3) AGENDA — ajoute "pour qui" + valeur par défaut pour "type"
--    (le nouveau design utilise start/end + by, mais les colonnes
--     time/duration/recurrence/exceptions existantes restent utilisées)
-- ---------------------------------------------------------------------
alter table public.calendrier_evenements
  add column if not exists by text not null default 'p1' check (by in ('p1', 'p2'));

alter table public.calendrier_evenements
  alter column type set default 'autre';


-- ---------------------------------------------------------------------
-- 4) IDÉES DATES — ajoute "fait ensemble"
--    (la colonne "mood" existante sert déjà de catégorie :
--     jazz / romantique / cozy / aventure / gourmand)
-- ---------------------------------------------------------------------
alter table public.idees_dates
  add column if not exists completed boolean not null default false;


-- ---------------------------------------------------------------------
-- 5) PETITS MOTS — ajoute "épinglé au widget"
-- ---------------------------------------------------------------------
alter table public.petits_mots
  add column if not exists widget boolean not null default false;


-- ---------------------------------------------------------------------
-- 6) BUDGET — enveloppe mensuelle (total) sur budget_params
--    (les dépenses détaillées vont dans la nouvelle table budget_depenses,
--     "spent" = somme des budget_depenses)
-- ---------------------------------------------------------------------
alter table public.budget_params
  add column if not exists enveloppe numeric not null default 0;

-- crée une ligne unique de paramètres si la table est vide
insert into public.budget_params (revenu_p1, revenu_p2, charges_fixes, enveloppe)
select 0, 0, '[]'::jsonb, 0
where not exists (select 1 from public.budget_params);


create table if not exists public.budget_depenses (
  id bigint generated by default as identity primary key,
  label text not null,
  amount numeric not null check (amount >= 0),
  by text not null check (by in ('p1', 'p2')),
  created_at timestamptz not null default now()
);

alter table public.budget_depenses enable row level security;

drop policy if exists "budget_depenses_select_authenticated" on public.budget_depenses;
create policy "budget_depenses_select_authenticated"
on public.budget_depenses for select
to authenticated
using (true);

drop policy if exists "budget_depenses_insert_authenticated" on public.budget_depenses;
create policy "budget_depenses_insert_authenticated"
on public.budget_depenses for insert
to authenticated
with check (true);

drop policy if exists "budget_depenses_delete_authenticated" on public.budget_depenses;
create policy "budget_depenses_delete_authenticated"
on public.budget_depenses for delete
to authenticated
using (true);


-- ---------------------------------------------------------------------
-- 7) MESSAGES "NOUS" — petit fil de discussion du couple
-- ---------------------------------------------------------------------
create table if not exists public.couple_messages (
  id bigint generated by default as identity primary key,
  content text not null,
  sender text not null check (sender in ('p1', 'p2')),
  created_at timestamptz not null default now()
);

alter table public.couple_messages enable row level security;

drop policy if exists "couple_messages_select_authenticated" on public.couple_messages;
create policy "couple_messages_select_authenticated"
on public.couple_messages for select
to authenticated
using (true);

drop policy if exists "couple_messages_insert_authenticated" on public.couple_messages;
create policy "couple_messages_insert_authenticated"
on public.couple_messages for insert
to authenticated
with check (true);

drop policy if exists "couple_messages_delete_authenticated" on public.couple_messages;
create policy "couple_messages_delete_authenticated"
on public.couple_messages for delete
to authenticated
using (true);


-- ---------------------------------------------------------------------
-- 8) RÉGLAGES DU COUPLE — surnom, "ensemble depuis", mascotte,
--    défi du jour partagé (ligne unique id = 1)
-- ---------------------------------------------------------------------
create table if not exists public.couple_settings (
  id bigint primary key default 1,
  nickname text,
  since date,
  mascot text default 'blobs',
  defi_jour jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint couple_settings_singleton check (id = 1)
);

insert into public.couple_settings (id) values (1)
on conflict (id) do nothing;

-- réutilise la fonction existante (créée par poesie_widget_messages.sql),
-- on la (re)crée ici au cas où elle n'existerait pas encore.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_couple_settings_updated_at on public.couple_settings;
create trigger set_couple_settings_updated_at
before update on public.couple_settings
for each row
execute function public.set_updated_at();

alter table public.couple_settings enable row level security;

drop policy if exists "couple_settings_select_authenticated" on public.couple_settings;
create policy "couple_settings_select_authenticated"
on public.couple_settings for select
to authenticated
using (true);

drop policy if exists "couple_settings_update_authenticated" on public.couple_settings;
create policy "couple_settings_update_authenticated"
on public.couple_settings for update
to authenticated
using (true)
with check (true);

drop policy if exists "couple_settings_insert_authenticated" on public.couple_settings;
create policy "couple_settings_insert_authenticated"
on public.couple_settings for insert
to authenticated
with check (true);


-- ---------------------------------------------------------------------
-- 9) PROFILS + APP_MEMBERS — auto-détection p1/p2
--    Crée automatiquement une ligne profiles + app_members pour chaque
--    nouvel utilisateur, et comble les lignes manquantes pour les
--    comptes déjà existants (1er compte créé = p1, 2e = p2).
-- ---------------------------------------------------------------------
-- l'email sert à retrouver l'adresse du/de la partenaire (messages, widget)
alter table public.profiles
  add column if not exists email text;

-- le nouveau design permet de renommer son profil librement (ex: "Bo"),
-- on retire donc la contrainte de longueur minimale sur "username".
alter table public.profiles
  drop constraint if exists profiles_username_check;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;

  insert into public.app_members (user_id) values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- backfill pour les comptes déjà créés
insert into public.profiles (id, email)
select id, email from auth.users
on conflict (id) do update set email = excluded.email;

insert into public.app_members (user_id)
select id from auth.users
on conflict (user_id) do nothing;

alter table public.app_members enable row level security;

drop policy if exists "app_members_select_authenticated" on public.app_members;
create policy "app_members_select_authenticated"
on public.app_members for select
to authenticated
using (true);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles for select
to authenticated
using (true);

-- le couple peut modifier les deux profils (ex: changer le prénom/avatar
-- de son/sa partenaire depuis Réglages), donc politiques permissives
-- comme pour les autres tables partagées du couple.
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_authenticated"
on public.profiles for insert
to authenticated
with check (true);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_authenticated"
on public.profiles for update
to authenticated
using (true)
with check (true);

-- =====================================================================
-- FIN DE LA MIGRATION
-- =====================================================================
