-- Table: petits_mots
-- Objectif: stocker des "petits mots" / phrases poétiques à partager.
-- Un mot peut être:
-- - partagé (recipient_email NULL) => visible par le couple
-- - adressé à une personne (recipient_email = email) => visible pour le destinataire + l'expéditeur

create table if not exists public.petits_mots (
  id bigint generated by default as identity primary key,
  content text not null,
  sender_email text not null,
  recipient_email text,
  created_at timestamptz not null default now()
);

create index if not exists petits_mots_created_at_idx on public.petits_mots (created_at desc);
create index if not exists petits_mots_sender_email_idx on public.petits_mots (sender_email);
create index if not exists petits_mots_recipient_email_idx on public.petits_mots (recipient_email);

-- RLS (recommandé)
alter table public.petits_mots enable row level security;

-- Politiques simples (couple): accessible aux utilisateurs authentifiés.
-- Si vous souhaitez cloisonner strictement, il faudra lier aux user_id (auth.uid()).
drop policy if exists "petits_mots_select_authenticated" on public.petits_mots;
create policy "petits_mots_select_authenticated"
on public.petits_mots for select
to authenticated
using (true);

drop policy if exists "petits_mots_insert_authenticated" on public.petits_mots;
create policy "petits_mots_insert_authenticated"
on public.petits_mots for insert
to authenticated
with check (true);

drop policy if exists "petits_mots_update_authenticated" on public.petits_mots;
create policy "petits_mots_update_authenticated"
on public.petits_mots for update
to authenticated
using (true)
with check (true);

drop policy if exists "petits_mots_delete_authenticated" on public.petits_mots;
create policy "petits_mots_delete_authenticated"
on public.petits_mots for delete
to authenticated
using (true);

